  function sacct { ssh $USER@$HOSTNAME sacct; }
  function sacctmgr { ssh $USER@$HOSTNAME sacctmgr; }
  function salloc { ssh $USER@$HOSTNAME salloc; }
  function sattach { ssh $USER@$HOSTNAME sattach; }
  function sbatch { ssh $USER@$HOSTNAME sbatch; }
  function scontrol { ssh $USER@$HOSTNAME scontrol; }
  function sdiag { ssh $USER@$HOSTNAME sdiag; }
  function sgather { ssh $USER@$HOSTNAME sgather; }
  function sinfo { ssh $USER@$HOSTNAME sinfo; }
  function smap { ssh $USER@$HOSTNAME smap; }	
  function sprio { ssh $USER@$HOSTNAME sprio; }
  function squeue { ssh $USER@$HOSTNAME squeue; }
  function sreport { ssh $USER@$HOSTNAME sreport; }
  function srun { ssh $USER@$HOSTNAME srun; }
  function sshare { ssh $USER@$HOSTNAME sshare; }           
  function sstat { ssh $USER@$HOSTNAME sstat; }           
  function strigger { ssh $USER@$HOSTNAME strigger; }           
  function sview { ssh $USER@$HOSTNAME sview; }  